### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by SteveJones92** [SE21-Team2/ClassMateBot#19]
The pinned messages don't allow seeing all of your tags or pinned messages. You simply have to remember it. For usability, there should be a way to find this information.

Look for more instances like this and try to generally improve usability.

**Comment by TanyaChu** [comment]
![image](https://user-images.githubusercontent.com/32313919/140243037-8e4c192c-5842-4fd9-85b0-6cccaf3f74ab.png)
![image](https://user-images.githubusercontent.com/32313919/140244316-7fac7ce4-32a7-444d-b8cf-b3b8b2d2dea1.png)
![image](https://user-images.githubusercontent.com/32313919/140254980-48641eed-7cd0-4eba-8481-3b8537679823.png)
![image](https://user-images.githubusercontent.com/32313919/140255106-07a4d952-4fb7-48c2-964e-b340fb2b0829.png)
![image](https://user-images.githubusercontent.com/32313919/140256002-0ae1f0c6-b84a-43a4-9f83-42356d47cc7b.png)

**Comment by TanyaChu** [comment]
![image](https://user-images.githubusercontent.com/32313919/140250549-8de514c0-d411-41fe-976c-6b43c7bd1edf.png)
![image](https://user-images.githubusercontent.com/32313919/140250910-3aa8d6cd-000d-4b51-949a-0c60f3464c3b.png)

**Comment by TanyaChu** [comment]
![image](https://user-images.githubusercontent.com/32313919/140251786-390e5656-4234-44f9-a663-32fad3d0fcb7.png)
![image](https://user-images.githubusercontent.com/32313919/140252700-18d6a7bd-11ad-468c-beee-a597ed5f4d10.png)
![image](https://user-images.githubusercontent.com/32313919/140256682-5d86ca22-402f-417d-b9f6-4328565cd1b4.png)
